### ISSUE TITLE
feature-0001 - conf - Auto-génération de port publique par le simulateur Kafka.

### ISSUE THREAD

**Issue by jetune** [leadware/kafka-embedded#1]
Dans la version actuelle, la classe de binding des propriétés du simulateur KAFKA va imposer la définition d'un port publique pour chacun des Listeners définit dans le fichier de propriété du Simulateur KAFKA.

Nous voulons désormais désactiver cette contrainte, c'est à dire permettre à un utilisateur de configurer un Listener Kafka sans forcément positionner un port d'accès public. Dans ce cas précis, lors de l'initialisation du Simulateur KAFKA, ce dernier devra rechercher dans le système un port libre pour chacun des Listeners ne disposant pas de port démarrer le listener en question sur ce port.

De plus, le simulateur devra proposer des getters, permettant d'accéder aux ports public de chaque Listener afin de permettre au Utilisateur de pouvoir configurer leur Producteurs/Consomateurs

**Comment by guytchatch** [comment]
J'ai démarré

**Comment by jetune** [comment]
resolved #1

**Comment by jetune** [comment]
resolved #6
